#!/bin/sh
#deploy="false"
deploy="true"

image=MsaResource
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t Resource/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push Resource/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag Resource/${image}:1.0-SNAPSHOT Resource/${image}:latest
        docker push Resource/${image}:latest
    fi
fi