#!/bin/sh
mvn clean package && docker build -t Resource/MsaResource .
docker rm -f MsaResource 2>/dev/null || true && docker run -it --name MsaResource -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MsaResource Resource/MsaResource
