#!/bin/sh
mvn clean package && docker build -t User-oprations/MsaUsersOp .
docker rm -f MsaUsersOp 2>/dev/null || true && docker run -it --name MsaUsersOp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MsaUsersOp User-oprations/MsaUsersOp
