#!/bin/sh
#deploy="false"
deploy="true"

image=MsaUsersOp
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t User-oprations/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push User-oprations/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag User-oprations/${image}:1.0-SNAPSHOT User-oprations/${image}:latest
        docker push User-oprations/${image}:latest
    fi
fi