#!/bin/sh
#deploy="false"
deploy="true"

image=MsaDoubt
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t doubt/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push doubt/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag doubt/${image}:1.0-SNAPSHOT doubt/${image}:latest
        docker push doubt/${image}:latest
    fi
fi