#!/bin/sh
mvn clean package && docker build -t doubt/MsaDoubt .
docker rm -f MsaDoubt 2>/dev/null || true && docker run -it --name MsaDoubt -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MsaDoubt doubt/MsaDoubt
