#!/bin/sh
#deploy="false"
deploy="true"

image=DoubtCart
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t Client-GUI/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push Client-GUI/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag Client-GUI/${image}:1.0-SNAPSHOT Client-GUI/${image}:latest
        docker push Client-GUI/${image}:latest
    fi
fi