#!/bin/sh
mvn clean package && docker build -t Client-GUI/DoubtCart .
docker rm -f DoubtCart 2>/dev/null || true && docker run -it --name DoubtCart -p 8080:8080 -p 4848:4848 -p 8181:8181 --name DoubtCart Client-GUI/DoubtCart
